### ISSUE TITLE
New Node is not created when cloud VM is destroyed

### ISSUE THREAD

**Issue by sohrab-** [openshift/machine-api-operator#347]
I am trying a simple resilience test. Is this a valid scenario?

I am new to this operator so sorry if this is a problem with the underlying provider and not the operator.

### Steps to reproduce

Terminate a work node EC2 instance in the AWS console.

### Excepted Behaviour

The operator detects this and spawns a new Node for that Machine.

### Actual Behaviour

EC2 instance is successfully created but the Machine still points to the old non-existent Node and no new Node is ever created (after even days).

### Additional information

Please note I retested this multiple times with the same results.

I am not sure relevant but I tried to "clear up" this inconsistent state by scaling the MachineSet to 0 and then back 1. This did create a new Machine and corresponding Node and EC2 instance but the old Machine is still there and it cannot even be deleted via CLI or Console.

Here is the immortal Machine's configuration

```yaml
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  creationTimestamp: "2019-06-20T06:54:48Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2019-07-10T03:12:57Z"
  finalizers:
  - machine.machine.openshift.io
  generateName: ocp4-plbsz-worker-ap-southeast-2a-
  generation: 2
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4-plbsz
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: ocp4-plbsz-worker-ap-southeast-2a
  name: ocp4-plbsz-worker-ap-southeast-2a-fptqg
  namespace: openshift-machine-api
  ownerReferences:
  - apiVersion: machine.openshift.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachineSet
    name: ocp4-plbsz-worker-ap-southeast-2a
    uid: 08bf6e32-9328-11e9-9f99-020bb2404310
  resourceVersion: "6926860"
  selfLink: /apis/machine.openshift.io/v1beta1/namespaces/openshift-machine-api/machines/ocp4-plbsz-worker-ap-southeast-2a-fptqg
  uid: 4b5afeb3-9328-11e9-9f99-020bb2404310
spec:
  metadata:
    creationTimestamp: null
  providerSpec:
    value:
      ami:
        id: ami-0d980796ce258b5d5
      apiVersion: awsproviderconfig.openshift.io/v1beta1
      blockDevices:
      - ebs:
          iops: 0
          volumeSize: 120
          volumeType: gp2
      credentialsSecret:
        name: aws-cloud-credentials
      deviceIndex: 0
      iamInstanceProfile:
        id: ocp4-plbsz-worker-profile
      instanceType: m4.large
      kind: AWSMachineProviderConfig
      metadata:
        creationTimestamp: null
      placement:
        availabilityZone: ap-southeast-2a
        region: ap-southeast-2
      publicIp: null
      securityGroups:
      - filters:
        - name: tag:Name
          values:
          - ocp4-plbsz-worker-sg
      subnet:
        filters:
        - name: tag:Name
          values:
          - ocp4-plbsz-private-ap-southeast-2a
      tags:
      - name: kubernetes.io/cluster/ocp4-plbsz
        value: owned
      userDataSecret:
        name: worker-user-data
status:
  addresses:
  - address: 10.0.130.185
    type: InternalIP
  - address: ""
    type: ExternalDNS
  - address: ip-10-0-130-185.ap-southeast-2.compute.internal
    type: InternalDNS
  lastUpdated: "2019-07-08T06:42:32Z"
  nodeRef:
    kind: Node
    name: ip-10-0-133-228.ap-southeast-2.compute.internal
    uid: 1ec1e629-9329-11e9-b98a-02df9d640d4c
  providerStatus:
    apiVersion: awsproviderconfig.openshift.io/v1beta1
    conditions:
    - lastProbeTime: "2019-06-20T06:56:30Z"
      lastTransitionTime: "2019-06-20T06:56:30Z"
      message: machine successfully created
      reason: MachineCreationSucceeded
      status: "True"
      type: MachineCreation
    instanceId: i-085307b37a9bd3227
    instanceState: running
    kind: AWSMachineProviderStatus
```

There are no interesting logs in any of the operator's pods. Here is the only thing that relates to the scenario from `machine-api-controllers`: 

```
E0710 03:15:50.715705       1 node_controller.go:90] Unable to retrieve Node /ip-10-0-143-38.ap-southeast-2.compute.internal from store: Node "ip-10-0-143-38.ap-southeast-2.compute.internal" not found
I0710 03:22:11.284616       1 controller.go:297] MachineSet "ocp4-plbsz-worker-ap-southeast-2a" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0710 03:22:31.437876       1 controller.go:297] MachineSet "ocp4-plbsz-worker-ap-southeast-2a" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
```

Please let me know if I should be capturing anything else.

OpenShift 4.1.4
Kubernetes v1.13.4+c62ce01

**Comment by vikaschoudhary16** [comment]
@sohrab- This a known behavior. Removing machine by deleting the cloud instance is not expected way. Machine should be removed through machineset only.

Now explanation for the behavior:
Newly created instance could not get registered as k8s node. Why? Because csr approver, https://github.com/openshift/cluster-machine-approver, did not approve the csr for the new instance as a security policy. And because it did not become node, machine object was also not updated to point to the new instance.
Why old machine not getting deleted? There is a finalizer on machine which does not let the machine deletion until succesful response from the cloud instance deletion api. In this case, i guess that would be returning an error because you deleted it from console and therefore machine not getting deleted.

/close

**Comment by sohrab-** [comment]
Thanks @vikaschoudhary16.

A few of more questions:

1. When you say "known behaviour", do you mean this is working as designed or a known bug?
1. If this is expected, is there any other way to protect against worker loss automatically?
1. How can we clean-up those orphan Machines now? The underlying instances are gone. Do I need to get into etcd for this?

**Comment by enxebre** [comment]
@sohrab- thanks for reporting feedback. The machine API is your source of truth for managing machines therefore terminate nodes via console is not recommended. As a workaround for the inconsistent status you have two choices:
1 - To add the ```machine.openshift.io/exclude-node-draining``` annotation to the orphan machine so then deletion will go through (this is fixed in new versions so there won't be need to add the annotation)
2 - Manually approve the new generated CSR via `kubectl certificate approve` so new instance becomes a node. This behaviour is likely to change soon in favour of no new instance being generated for the old machine object. So we encourage to delete corrupted a machines and let the MachineSet to create a new one.
 
> If this is expected, is there any other way to protect against worker loss automatically (self-healing)?

There's a "tech preview" feature "Machine health checking" where you can targets machines that you want to be self-healed and automatically recreated when a problem is detected
